global:
  message: Welcome to customer service dev Environment!!
server:
  port:
    8082
message: Hello from dev!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cust_dev
    data-username: root
    data-password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      
