global:
  message: Welcome to Order service prod Environment!!
server:
  port:
    8085
message: Hello from Order prod!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_prod
    data-username: root
    data-password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
