global:
  message: Welcome to Order service dev Environment!!
server:
  port:
    8084
message: Hello from Order dev!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_master
    data-username: root
    data-password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      
